export const FETCH_QUIZZES_START = 'FETCH_QUIZZES_START'
export const LOAD_QUIZZES = 'LOAD_QUIZZES'
export const FETCH_QUIZZES_ERROR = 'FETCH_QUIZZES_ERROR'
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'
export const FETCH_NEXT_QUESTION = 'FETCH_NEXT_QUESTION'
export const FETCH_QUIZ_FINISH = 'FETCH_QUIZ_FINISH'
export const FETCH_REFRESH_QUIZ = 'FETCH_REFRESH_QUIZ'

export const CREATE_QUESTION = 'CREATE_QUESTION'
export const CLEAR_QUIZ = 'CLEAR_QUIZ'

export const AUTH_SIGN_IN = 'AUTH_SIGN_IN'
export const LOG_OUT = 'LOG_OUT'

